COMPONENT_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

include ../../mk/component-tests.mk

.PHONY: help
help:
	@echo "dreo_tuya_mcu component"
	@echo "  test       Run host GoogleTest suite (dreo_tuya_protocol)"
